name: SBStrips
version: "v0.6.5"
license: "GPL-2.0-or-later"
date: 2021-02-24
description: |
    for syzygies of string modules over special biserial algebras

authors:
    - name: Joe Allen
      url: https://research-information.bris.ac.uk/en/persons/joe-allen

maintainers:
    - name: Joe Allen
      url: https://research-information.bris.ac.uk/en/persons/joe-allen

GAP: ">=4.11"

needed-pkgs:
    - name: "qpa"
      version: "1.30"
    - name: "GAPDoc"
      version: ">=1.6"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://github.com/jw-allen/sbstrips
readme: README
packageinfo: https://github.com/jw-allen/sbstrips/blob/master/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/jw-allen/sbstrips/archive/v0.6.5.tar.gz

abstract: |
    String modules for special biserial (SB) algebras are represented by string graphs. Many modules related to a given string module, including its syzygy, transpose and vector-space dual and hence Auslander-Reiten translate and inverse translate, are also string modules. These related modules can be calculated combinatorially rather than algebraically. SBStrips implements this functionality in GAP, representing string graphs as objects called strips. It includes some tests for associated properties such as syzygy type, delooping level and weak periodicity.
    
     SBStrips also includes bookkeeping functionality for multisets, which it calls collected lists, and it integrates with (and depends on) the QPA package for quiver algebras and their modules.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/main.pdf
keywords: |
    special biserial algebra, string module, syzygy.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>All21</span>]   <b class='BibAuthor'>Allen, J.</b>,
     <i class='BibTitle'>SBStrips, for syzygies of string modules over special biserial algebras,
             Version v0.6.5</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/jw-allen/sbstrips">https://github.com/jw-allen/sbstrips</a></span>.
    </p>
    

bibtex: |
    @misc{ SBStripsv0.6.5,
      author =           {Allen, J.},
      title =            {{SBStrips},  for  syzygies  of  string modules over special biserial algebras,
                          {V}ersion v0.6.5},
      month =            {Feb},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href                                   {https://github.com/jw-allen/sbstrips}
                          {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{jw-allen/}\discretionary {}{}{}\texttt{sbstrips}}},
      keywords =         {special biserial algebra; string module; syzygy},
      printedkey =       {All21}
    }

